/**
 *
 * @file room_event.hpp
 * @author Gaspard Kirira
 * @brief Authoritative event representation for Vix Realtime rooms.
 *
 * Copyright 2026, Gaspard Kirira. All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 *
 * Vix.cpp
 *
 */

#ifndef VIX_REALTIME_ROOM_EVENT_HPP
#define VIX_REALTIME_ROOM_EVENT_HPP

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include <vix/realtime/api.hpp>
#include <vix/realtime/event_audience.hpp>
#include <vix/realtime/event_id.hpp>
#include <vix/realtime/room_id.hpp>
#include <vix/realtime/room_version.hpp>
#include <vix/realtime/session_id.hpp>
#include <vix/realtime/types.hpp>

namespace vix::realtime
{
  /**
   * @brief Represents one authoritative change produced by a room handler.
   *
   * Room events are generated by the server after command validation. They are
   * persisted before being applied to room state and delivered to sessions.
   */
  class VIX_REALTIME_API RoomEvent
  {
  public:
    /**
     * @brief Maximum number of characters allowed in an event type.
     */
    static constexpr std::size_t max_type_size = 128;

    /**
     * @brief Construct an empty room event.
     *
     * The resulting event is not valid until all required fields are set.
     */
    RoomEvent() = default;

    /**
     * @brief Construct a room event.
     *
     * @param roomId Room stream owning the event.
     * @param type Application-defined event type.
     * @param payload Event payload.
     * @param audience Delivery audience.
     */
    RoomEvent(
        RoomId roomId,
        std::string type,
        JsonObject payload = {},
        EventAudience audience = EventAudience::Room);

    /**
     * @brief Return the persistent event identifier.
     *
     * @return Event identifier, or zero before persistence.
     */
    [[nodiscard]] EventId event_id() const noexcept;

    /**
     * @brief Return the room owning the event.
     *
     * @return Room identifier.
     */
    [[nodiscard]] const RoomId &room_id() const noexcept;

    /**
     * @brief Return the room version produced by this event.
     *
     * @return Version after the event is applied.
     */
    [[nodiscard]] RoomVersion room_version() const noexcept;

    /**
     * @brief Return the application-defined event type.
     *
     * @return Event type.
     */
    [[nodiscard]] const std::string &type() const noexcept;

    /**
     * @brief Return the event payload.
     *
     * @return Constant reference to the event payload.
     */
    [[nodiscard]] const JsonObject &payload() const noexcept;

    /**
     * @brief Return mutable access to the event payload.
     *
     * This is intended for event construction before persistence. A persisted
     * event must be treated as immutable.
     *
     * @return Mutable reference to the event payload.
     */
    [[nodiscard]] JsonObject &payload() noexcept;

    /**
     * @brief Return the event delivery audience.
     *
     * @return Event audience.
     */
    [[nodiscard]] EventAudience audience() const noexcept;

    /**
     * @brief Return the explicitly targeted session.
     *
     * This value is used only when the audience is `EventAudience::Session`.
     *
     * @return Target session, when present.
     */
    [[nodiscard]] const std::optional<SessionId> &
    target_session() const noexcept;

    /**
     * @brief Return the session that caused the event.
     *
     * @return Originating session, when available.
     */
    [[nodiscard]] const std::optional<SessionId> &
    source_session() const noexcept;

    /**
     * @brief Return the originating client request identifier.
     *
     * @return Request identifier, or an empty string when unavailable.
     */
    [[nodiscard]] const RequestId &request_id() const noexcept;

    /**
     * @brief Return the correlation identifier.
     *
     * @return Correlation identifier, or an empty string when unavailable.
     */
    [[nodiscard]] const CorrelationId &correlation_id() const noexcept;

    /**
     * @brief Return the event schema version.
     *
     * @return Schema version.
     */
    [[nodiscard]] SchemaVersion schema_version() const noexcept;

    /**
     * @brief Return the event creation timestamp.
     *
     * @return Event creation timestamp.
     */
    [[nodiscard]] Timestamp created_at() const noexcept;

    /**
     * @brief Return application-defined event metadata.
     *
     * @return Constant reference to event metadata.
     */
    [[nodiscard]] const JsonObject &metadata() const noexcept;

    /**
     * @brief Assign the persistent event identifier.
     *
     * This is normally performed by the event store or room runtime.
     *
     * @param value Persistent event identifier.
     * @return Current event.
     */
    RoomEvent &set_event_id(EventId value) noexcept;

    /**
     * @brief Assign the room version produced by this event.
     *
     * @param value Room version after event application.
     * @return Current event.
     */
    RoomEvent &set_room_version(RoomVersion value) noexcept;

    /**
     * @brief Set the event delivery audience.
     *
     * @param value Delivery audience.
     * @return Current event.
     */
    RoomEvent &set_audience(EventAudience value) noexcept;

    /**
     * @brief Set the explicitly targeted session.
     *
     * Setting a target does not automatically change the audience.
     *
     * @param value Target logical session.
     * @return Current event.
     */
    RoomEvent &set_target_session(SessionId value);

    /**
     * @brief Remove the explicitly targeted session.
     *
     * @return Current event.
     */
    RoomEvent &clear_target_session() noexcept;

    /**
     * @brief Set the session that caused the event.
     *
     * @param value Originating logical session.
     * @return Current event.
     */
    RoomEvent &set_source_session(SessionId value);

    /**
     * @brief Remove the originating session.
     *
     * @return Current event.
     */
    RoomEvent &clear_source_session() noexcept;

    /**
     * @brief Set the originating client request identifier.
     *
     * @param value Request identifier.
     * @return Current event.
     */
    RoomEvent &set_request_id(RequestId value);

    /**
     * @brief Set the event correlation identifier.
     *
     * @param value Correlation identifier.
     * @return Current event.
     */
    RoomEvent &set_correlation_id(CorrelationId value);

    /**
     * @brief Set the event schema version.
     *
     * @param value Non-zero schema version.
     * @return Current event.
     */
    RoomEvent &set_schema_version(SchemaVersion value);

    /**
     * @brief Set the event creation timestamp.
     *
     * @param value Event creation timestamp.
     * @return Current event.
     */
    RoomEvent &set_created_at(Timestamp value) noexcept;

    /**
     * @brief Replace application-defined event metadata.
     *
     * @param value Event metadata.
     * @return Current event.
     */
    RoomEvent &set_metadata(JsonObject value);

    /**
     * @brief Return whether the event contains all required valid fields.
     *
     * This validation does not require a persistent event ID. Events may be
     * valid before being appended to a store.
     *
     * @return True when the event is valid.
     */
    [[nodiscard]] bool is_valid() const noexcept;

    /**
     * @brief Validate the event.
     *
     * @throws vix::realtime::Error
     *         When a required field or delivery rule is invalid.
     */
    void validate() const;

    /**
     * @brief Return whether an application-defined event type is valid.
     *
     * Valid event types use dot-separated names such as:
     *
     * @code
     * object.placed
     * citizen.moved
     * message.sent
     * @endcode
     *
     * @param value Candidate event type.
     * @return True when the event type is valid.
     */
    [[nodiscard]] static bool is_valid_type(
        std::string_view value) noexcept;

  private:
    /** @brief Persistent ordered event identifier. */
    EventId eventId_{};

    /** @brief Room stream owning the event. */
    RoomId roomId_{};

    /** @brief Room version after this event is applied. */
    RoomVersion roomVersion_{};

    /** @brief Application-defined event type. */
    std::string type_{};

    /** @brief Application-defined event payload. */
    JsonObject payload_{};

    /** @brief Event delivery audience. */
    EventAudience audience_{EventAudience::Room};

    /** @brief Explicit target for session-scoped delivery. */
    std::optional<SessionId> targetSession_{};

    /** @brief Logical session that caused the event. */
    std::optional<SessionId> sourceSession_{};

    /** @brief Originating client request identifier. */
    RequestId requestId_{};

    /** @brief Correlation identifier shared with related operations. */
    CorrelationId correlationId_{};

    /** @brief Application event schema version. */
    SchemaVersion schemaVersion_{1};

    /** @brief Time at which the event was created. */
    Timestamp createdAt_{SystemClock::now()};

    /** @brief Non-authoritative event metadata. */
    JsonObject metadata_{};
  };

} // namespace vix::realtime

#endif // VIX_REALTIME_ROOM_EVENT_HPP
