/**
 *
 * @file token_generator.hpp
 * @author Gaspard Kirira
 * @brief URL-safe opaque token generation for Vix Realtime.
 *
 * Copyright 2026, Gaspard Kirira. All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 *
 * Vix.cpp
 *
 */

#ifndef VIX_REALTIME_INTERNAL_TOKEN_GENERATOR_HPP
#define VIX_REALTIME_INTERNAL_TOKEN_GENERATOR_HPP

#include <cstddef>
#include <cstdint>
#include <functional>
#include <mutex>
#include <string>
#include <string_view>

#include <vix/realtime/types.hpp>

namespace vix::realtime::internal
{
  /**
   * @brief Generates opaque URL-safe tokens from random entropy.
   *
   * Generated tokens use unpadded Base64 URL encoding and may contain:
   *
   * - uppercase and lowercase ASCII letters;
   * - decimal digits;
   * - `-`;
   * - `_`;
   * - one optional `.` separating the configured prefix.
   *
   * The generator is thread-safe. A custom random source may be injected for
   * deterministic tests or platform-specific secure entropy providers.
   */
  class TokenGenerator
  {
  public:
    /**
     * @brief Function that fills a byte buffer with random data.
     *
     * The function must initialize exactly `size` bytes beginning at `data`.
     */
    using RandomSource =
        std::function<void(
            std::uint8_t *data,
            std::size_t size)>;

    /** @brief Default random entropy size in bytes. */
    static constexpr std::size_t defaultEntropyBytes{32};

    /** @brief Minimum accepted entropy size in bytes. */
    static constexpr std::size_t minimumEntropyBytes{16};

    /** @brief Maximum accepted entropy size in bytes. */
    static constexpr std::size_t maximumEntropyBytes{128};

    /** @brief Maximum accepted token prefix length. */
    static constexpr std::size_t maximumPrefixSize{32};

    /**
     * @brief Construct a token generator using the default random source.
     *
     * The default source uses `std::random_device`.
     *
     * @param entropyBytes Number of random bytes encoded in each token.
     * @param prefix Optional token prefix. An empty prefix is permitted.
     *
     * @throws vix::realtime::Error
     *         When entropy size or prefix is invalid.
     */
    explicit TokenGenerator(
        std::size_t entropyBytes = defaultEntropyBytes,
        std::string prefix = "rt");

    /**
     * @brief Construct a token generator using a custom random source.
     *
     * @param randomSource Function used to fill random byte buffers.
     * @param entropyBytes Number of random bytes encoded in each token.
     * @param prefix Optional token prefix. An empty prefix is permitted.
     *
     * @throws vix::realtime::Error
     *         When the random source, entropy size, or prefix is invalid.
     */
    TokenGenerator(
        RandomSource randomSource,
        std::size_t entropyBytes = defaultEntropyBytes,
        std::string prefix = "rt");

    TokenGenerator(const TokenGenerator &) = delete;
    TokenGenerator &operator=(const TokenGenerator &) = delete;
    TokenGenerator(TokenGenerator &&) = delete;
    TokenGenerator &operator=(TokenGenerator &&) = delete;

    /**
     * @brief Generate one opaque URL-safe token.
     *
     * @return Newly generated token.
     *
     * @throws vix::realtime::Error
     *         When secure random bytes cannot be generated.
     */
    [[nodiscard]] ResumeToken generate() const;

    /**
     * @brief Return whether a token matches this generator's exact format.
     *
     * The token must contain the configured prefix and the exact encoded
     * payload length for `entropy_bytes()`.
     *
     * @param token Token to inspect.
     * @return True when the token matches this generator.
     */
    [[nodiscard]] bool accepts(
        std::string_view token) const noexcept;

    /**
     * @brief Return whether text has valid opaque token syntax.
     *
     * This validates syntax only. It does not verify token authenticity,
     * expiration, ownership, or expected entropy length.
     *
     * @param token Token text to inspect.
     * @return True when the text contains only permitted token characters.
     */
    [[nodiscard]] static bool is_valid(
        std::string_view token) noexcept;

    /**
     * @brief Return the configured random entropy size.
     *
     * @return Entropy size in bytes.
     */
    [[nodiscard]] std::size_t
    entropy_bytes() const noexcept;

    /**
     * @brief Return the configured token prefix.
     *
     * @return Token prefix, or an empty string.
     */
    [[nodiscard]] const std::string &
    prefix() const noexcept;

    /**
     * @brief Return the exact size of tokens generated by this instance.
     *
     * @return Generated token size in characters.
     */
    [[nodiscard]] std::size_t
    token_size() const noexcept;

  private:
    /**
     * @brief Validate generator configuration.
     */
    void validate() const;

    /**
     * @brief Return the unpadded Base64 URL size for a byte count.
     */
    [[nodiscard]] static constexpr std::size_t
    encoded_size(std::size_t byteCount) noexcept
    {
      const std::size_t completeGroups =
          byteCount / 3;

      const std::size_t remainder =
          byteCount % 3;

      return completeGroups * 4 +
             (remainder == 0
                  ? 0
                  : remainder + 1);
    }

    /** @brief Number of random bytes included in each token. */
    std::size_t entropyBytes_{defaultEntropyBytes};

    /** @brief Optional token namespace prefix. */
    std::string prefix_{"rt"};

    /** @brief Optional injected random byte source. */
    mutable RandomSource randomSource_{};

    /** @brief Serializes access to the random source. */
    mutable std::mutex mutex_{};
  };

} // namespace vix::realtime::internal

#endif // VIX_REALTIME_INTERNAL_TOKEN_GENERATOR_HPP
